INSERT INTO dog(id, name, description) VALUES (97, 'Rocky', 'A brown Chihuahua known for being protective.');
INSERT INTO dog(id, name, description) VALUES (87, 'Bailey', 'A tan Dachshund known for being playful.');
INSERT INTO dog(id, name, description) VALUES (89, 'Charlie', 'A black Bulldog known for being curious.');
INSERT INTO dog(id, name, description) VALUES (67, 'Cooper', 'A tan Boxer known for being affectionate.');
INSERT INTO dog(id, name, description) VALUES (73, 'Max', 'A brindle Dachshund known for being energetic.');
INSERT INTO dog(id, name, description) VALUES (3, 'Buddy', 'A Poodle known for being calm.');
INSERT INTO dog(id, name, description) VALUES (93, 'Duke', 'A white German Shepherd known for being friendly.');
INSERT INTO dog(id, name, description) VALUES (63, 'Jasper', 'A grey Shih Tzu known for being protective.');
INSERT INTO dog(id, name, description) VALUES (69, 'Toby', 'A grey Doberman known for being playful.');
INSERT INTO dog(id, name, description) VALUES (101, 'Nala', 'A spotted German Shepherd known for being loyal.');
INSERT INTO dog(id, name, description) VALUES (61, 'Penny', 'A white Great Dane known for being protective.');
INSERT INTO dog(id, name, description) VALUES (1, 'Bella', 'A golden Poodle known for being calm.');
